name: queryselector
version: git
summary: Command line DOM query tool
description: |
  Get some content from the web:-
    $ queryselector https://github.com/nottrobin ".user-profile-bio"

base: core18
confinement: strict

parts:
  queryselector:
    plugin: nodejs
    nodejs-package-manager: npm
    nodejs-version: 10.18.0
    source: .

apps:
  queryselector:
    command: queryselector
    plugs:
      - network
      - network-bind
